# Generated by Django 5.1.5 on 2025-01-15 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('uid', models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('cpu', models.PositiveIntegerField(verbose_name='Количество ядер CPU')),
                ('ram', models.PositiveIntegerField(verbose_name='Объем RAM (ГБ)')),
                ('hdd', models.PositiveIntegerField(verbose_name='Объем HDD (ГБ)')),
                ('status', models.CharField(choices=[('started', 'Запущен'), ('blocked', 'Заблокирован'), ('stopped', 'Остановлен')], default='stopped', max_length=10, verbose_name='Статус сервера')),
            ],
            options={
                'verbose_name': 'Сервер',
                'verbose_name_plural': 'Серверы',
            },
        ),
    ]
