# Generated by Django 5.1.5 on 2025-01-15 11:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='cpu',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(128)], verbose_name='Количество ядер CPU'),
        ),
        migrations.AlterField(
            model_name='server',
            name='hdd',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(10240)], verbose_name='Объем HDD (ГБ)'),
        ),
        migrations.AlterField(
            model_name='server',
            name='ram',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1024)], verbose_name='Объем RAM (ГБ)'),
        ),
    ]
