# Generated by Django 5.1.5 on 2025-01-15 11:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_alter_server_cpu_alter_server_hdd_alter_server_ram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
