# Generated by Django 5.1.5 on 2025-01-15 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_alter_server_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='uid',
        ),
        migrations.AddField(
            model_name='server',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
